- name: My First Play
  hosts: next_cloud_servers
  tasks:
    - name: update all packages
      apt:
        name: "*"
        state: latest

    - name: install python3-apt
      package:
          name: python3-apt
          state: present

    - name: install apache
      apt:
        name: apache2
        state: present


    - name: Configuring apache
      file:
        src: /templates/nextcloud.conf.j2
        dest: /etc/apache2/sites_available/nextcloud.conf
      notify: restart apache

    - name: install php and modules
      apt:
        pkg:
          - php
          - php-curl
          - php-dompdf
          - php-gd
          - php-mbstring
          - php-zip
          - php-intl
          - php-ldap
          - php-imap
          - php-bcmath
          - php-gmp
          - php-imagick
          - php-phar
        state: present

    - name: install ffmpeg
      apt:
        name: ffmpeg
        state: present

    - name: install libreOffice
      apt:
        name: libreoffice
        state: present

    - name: install mariaDB
      apt:
        name: mariadb-server
        state: present

    - name: restart apache
      service:
        name: apache2
        state: restarted
